FROM docker.io/golang:1.24-alpine3.21 as build
RUN apk upgrade --no-cache
RUN apk add tzdata make git
WORKDIR /workspace
COPY . .
RUN GO_BUILD_PACKAGES=./cmd/instaslice-webhook make

FROM docker.io/alpine:3.21
RUN apk upgrade --no-cache
RUN apk add tzdata make
WORKDIR /
COPY --from=build /workspace/instaslice-webhook /usr/bin
USER 65532:65532

ARG NAME=instaslice-webhook
ARG DESCRIPTION="The Instaslice webhook."

# Licenses
COPY LICENSE /licenses/LICENSE
