apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: das-scheduler-authentication-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: das-operator
- kind: ServiceAccount
  name: das-scheduler
  namespace: das-operator
- kind: ServiceAccount
  name: secondary-scheduler
  namespace: openshift-secondary-scheduler-operator
roleRef:
  kind: ClusterRole
  name: system:extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
