apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: das-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: das-scheduler
subjects:
- kind: ServiceAccount
  name: das-scheduler
  namespace: das-operator
