apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: das-scheduler
rules:
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - update
  - patch
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  - replicasets
  verbs:
  - create
  - update
  - patch
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/binding
  - pods/status
  verbs:
  - create
  - update
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services
  - persistentvolumeclaims
  - replicationcontrollers
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - inference.redhat.com
  resources:
  - nodeaccelerators
  - nodeaccelerators/status
  - dasoperators
  - dasoperators/status
  - allocationclaims
  - allocationclaims/status
  - allocationclaims/finalizers
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  - csidrivers
  - csistoragecapacities
  - storageclasses
  - volumeattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
