---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: das-scheduler
subjects:
  - kind: ServiceAccount
    name: das-scheduler
    namespace: das-operator
  - kind: ServiceAccount
    name: secondary-scheduler
    namespace: openshift-secondary-scheduler-operator
roleRef:
  kind: ClusterRole
  name: das-scheduler
  apiGroup: rbac.authorization.k8s.io
