apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instaslice-operator-operand
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: instaslice-operator-operand
subjects:
  - kind: ServiceAccount
    name: instaslice-operator-operand
    namespace: instaslice-system
