apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: instaslice-scheduler
  namespace: instaslice-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]