apiVersion: inference.redhat.com/v1alpha1
kind: InstasliceOperator
metadata:
  name: cluster
  namespace: das-operator
spec:
  managementState: Managed
  logLevel: Normal
  operatorLogLevel: Normal
  emulatedMode: "$(EMULATED_MODE)"
