allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- ALL
apiVersion: security.openshift.io/v1
fsGroup:
  type: RunAsAny
kind: SecurityContextConstraints
metadata:
  name: das-operator
  namespace: das-operator
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
