apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: das-operator
rules:
  - apiGroups:
      - inference.redhat.com
    resources:
      - nodeaccelerators
      - nodeaccelerators/status
      - nodeaccelerators/finalizers
      - dasoperators
      - dasoperators/status
      - dasoperators/finalizers
      - allocationclaims
      - allocationclaims/status
      - allocationclaims/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csistoragecapacities
      - csidrivers
      - csinodes
      - storageclasses
      - volumeattachments
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - replicationcontrollers
      - pods/binding
      - pods/status
    verbs:
      - get
      - list
      - create
      - watch
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - namespaces
      - secrets
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - config.openshift.io
    resources:
      - infrastructures
    verbs:
      - get
  - apiGroups:
    - cert-manager.io
    resources:
    - certificates
    - issuers
    verbs:
    - create
    - get
    - list
    - patch
    - update
  - apiGroups:
    - events.k8s.io
    resources:
    - events
    verbs:
    - create
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    verbs:
    - create
    - update
    - patch
    - list
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: das-operator
subjects:
  - kind: ServiceAccount
    name: das-operator
    namespace: das-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: das-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: das-operator-privileged-scc
subjects:
- kind: ServiceAccount
  name: das-operator
  namespace: das-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: das-operator
  namespace: das-operator
rules:
- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: das-operator
  namespace: das-operator
subjects:
- kind: ServiceAccount
  name: das-operator
  namespace: das-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: das-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: das-operator-authentication-reader
subjects:
- kind: ServiceAccount
  name: das-operator
  namespace: das-operator
roleRef:
  kind: ClusterRole
  name: system:extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
