apiVersion: apps/v1
kind: Deployment
metadata:
  name: das-operator
  namespace: das-operator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: das-operator
  template:
    metadata:
      labels:
        app: das-operator
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: das-operator
            weight: 100
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: instaslice-operator
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
          image: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-operator-next:latest
          volumeMounts:
            - name: tmp
              mountPath: "/tmp"
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - /usr/bin/das-operator
          args:
            - "operator"
          imagePullPolicy: Always
          env:
            - name: OPERATOR_NAME
              value: "das-operator"
            - name: RELATED_IMAGE_DAEMONSET_IMAGE
              value: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-daemonset-next:latest
            - name: RELATED_IMAGE_WEBHOOK_IMAGE
              value: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-webhook-next:latest
            - name: RELATED_IMAGE_SCHEDULER_IMAGE
              value: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-scheduler-next:latest
      serviceAccountName: das-operator
      volumes:
        - name: tmp
          emptyDir: {}
