apiVersion: apps/v1
kind: Deployment
metadata:
  name: instaslice-operator
  namespace: instaslice-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instaslice-operator
  template:
    metadata:
      labels:
        app: instaslice-operator
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: instalice-operator
            weight: 100
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: instaslice-operator
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
          image: quay.io/ryan.phillips/instaslice-operator
          volumeMounts:
            - name: tmp
              mountPath: "/tmp"
          ports:
            - containerPort: 60000
              name: metrics
          command:
            - /usr/bin/instaslice-operator
          args:
            - "operator"
          imagePullPolicy: Always
          env:
            - name: OPERATOR_NAME
              value: "instaslice-operator"
            - name: RELATED_IMAGE_DAEMONSET_IMAGE
              value: quay.io/ryan.phillips/instaslice-daemonset
            - name: RELATED_IMAGE_WEBHOOK_IMAGE
              value: quay.io/ryan.phillips/instaslice-webhook
      serviceAccountName: instaslice-operator
      volumes:
        - name: tmp
          emptyDir: {}
