apiVersion: v1
kind: Service
metadata:
  name: instaslice-metrics
  namespace: instaslice-system
  labels:
    control-plane: controller-manager
spec:
  ports:
    - name: metrics
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    control-plane: controller-manager  # Use the correct label here