apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-metrics-binding
  namespace: instaslice-system
subjects:
- kind: ServiceAccount
  name: prometheus-kube-prometheus-prometheus  # Change this to your Prometheus ServiceAccount
  namespace: instaslice-monitoring  # Change to Prometheus namespace
roleRef:
  kind: Role
  name: prometheus-metrics-reader
  apiGroup: rbac.authorization.k8s.io
