apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "inference.redhat.com/v1alpha1",
          "kind": "DASOperator",
          "metadata": {
            "name": "cluster",
            "namespace": "das-operator"
          },
          "spec": {
            "emulatedMode": "enabled",
            "logLevel": "Normal",
            "managementState": "Managed",
            "operatorLogLevel": "Normal"
          }
        }
      ]
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.openshift.io/valid-subscription: '["OpenShift Kubernetes Engine", "OpenShift Container Platform", "OpenShift Platform Plus"]'
    capabilities: Basic Install
    categories: Drivers and plugins
    containerImage: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-operator-next:latest
    createdAt: "2025-04-23T17:42:28Z"
    description: InstaSlice works with GPU operator to create mig slices on demand
    operators.operatorframework.io/builder: operator-sdk-v1.38.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    repository: https://github.com/openshift/instaslice-operator
    support: https://github.com/openshift/instaslice-operator/issues
  name: das-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: DASOperator
      name: dasoperators.inference.redhat.com
      version: v1alpha1
    - kind: NodeAccelerator
      name: nodeaccelerators.inference.redhat.com
      version: v1alpha1
  description: Das Operator description. TODO.
  displayName: Das Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - inference.redhat.com
          resources:
          - nodeaccelerators
          - nodeaccelerators/status
          - nodeaccelerators/finalizers
          - dasoperators
          - dasoperators/status
          - dasoperators/finalizers
          - allocationclaims
          - allocationclaims/status
          - allocationclaims/finalizers
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          - replicasets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          - clusterrolebindings
          - roles
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - validatingwebhookconfigurations
          - mutatingwebhookconfigurations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          - configmaps
          - events
          - namespaces
          - secrets
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - config.openshift.io
          resources:
          - infrastructures
          verbs:
          - get
        - apiGroups:
          - cert-manager.io
          resources:
          - certificates
          - issuers
          verbs:
          - create
          - get
          - list
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          - pods
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes
          - nodes/status
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - inference.redhat.com
          resources:
          - nodeaccelerators
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - inference.redhat.com
          resources:
          - nodeaccelerators/finalizers
          verbs:
          - update
        - apiGroups:
          - inference.redhat.com
          resources:
          - nodeaccelerators/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - list
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - create
          - get
          - update
          - watch
        - apiGroups:
          - cert-manager.io
          resources:
          - certificates
          - issuers
          verbs:
          - create
          - get
          - list
          - patch
          - update
        serviceAccountName: das-operator
      - rules:
        - apiGroups:
          - ""
          resourceNames:
          - extension-apiserver-authentication
          resources:
          - configmaps
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - pods/binding
          - pods/status
          verbs:
          - create
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          - events.k8s.io
          resources:
          - events
          verbs:
          - create
          - patch
          - update
        - apiGroups:
          - inference.redhat.com
          resources:
          - nodeaccelerators
          - nodeaccelerators/status
          - dasoperators
          - dasoperators/status
          - allocationclaims
          - allocationclaims/status
          - allocationclaims/finalizers
          verbs:
          - get
          - list
          - watch
          - update
          - patch
          - create
          - delete
        - apiGroups:
          - storage.k8s.io
          resources:
          - csinodes
          - csidrivers
          - csistoragecapacities
          - storageclasses
          - volumeattachments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
        serviceAccountName: das-scheduler
      deployments:
      - name: das-operator
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: das-operator
          strategy: {}
          template:
            metadata:
              labels:
                app: das-operator
            spec:
              affinity:
                podAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - podAffinityTerm:
                      labelSelector:
                        matchLabels:
                          app: das-operator
                      topologyKey: kubernetes.io/hostname
                    weight: 100
              containers:
              - args:
                - operator
                command:
                - /usr/bin/das-operator
                env:
                - name: OPERATOR_NAME
                  value: das-operator
                - name: RELATED_IMAGE_DAEMONSET_IMAGE
                  value: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-daemonset-next:latest
                - name: RELATED_IMAGE_WEBHOOK_IMAGE
                  value: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-webhook-next:latest
                - name: RELATED_IMAGE_SCHEDULER_IMAGE
                  value: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-scheduler-next:latest
                image: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-operator-next:latest
                imagePullPolicy: Always
                name: instaslice-operator
                ports:
                - containerPort: 60000
                  name: metrics
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  readOnlyRootFilesystem: true
                volumeMounts:
                - mountPath: /tmp
                  name: tmp
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: das-operator
              volumes:
              - emptyDir: {}
                name: tmp
      - name: das-scheduler
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: das-scheduler
          strategy: {}
          template:
            metadata:
              labels:
                app: das-scheduler
            spec:
              containers:
              - args:
                - --config=/etc/das-scheduler/config.yaml
                command:
                - das-scheduler
                image: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-scheduler-next:latest
                imagePullPolicy: Always
                name: scheduler
                resources: {}
                volumeMounts:
                - mountPath: /etc/das-scheduler
                  name: config
              serviceAccountName: das-scheduler
              volumes:
              - configMap:
                  name: das-scheduler-config
                name: config
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        serviceAccountName: das-scheduler
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - das-operator
  links:
  - name: Das Operator
    url: https://das-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  relatedImages:
  - image: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-daemonset-next:latest
    name: daemonset-image
  - image: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-webhook-next:latest
    name: webhook-image
  - image: quay.io/redhat-user-workloads/dynamicacceleratorsl-tenant/instaslice-scheduler-next:latest
    name: scheduler-image
  version: 0.1.0
