apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: das-operator-authentication-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: das-operator
  namespace: das-operator
