apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: system:openshift:scc:instaslice-operator-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - instaslice-operator-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
