apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd-1
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vectoradd-1
    image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0-ubi8"
    resources:
      limits:
        nvidia.com/mig-1g.5gb: 1
    command:
      - sh
      - -c
      -  "nvidia-smi -L; /cuda-samples/vectorAdd && sleep 180"
      # requests:
      #   cpu: 1000m
      #   memory: 512Mi
