apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: scc
allowPrivilegedContainer: true
allowedCapabilities:
- "ALL"
allowPrivilegeEscalation: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
readOnlyRootFilesystem: true
