apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - instaslice-operator-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
